### ISSUE TITLE
Slicing for AADL Models: Initialization

### ISSUE THREAD

**Issue by sprocter** [osate/osate2#2715]
[Awas](https://awas.sireum.org/) demonstrated the value and utility of slicing AADL models. But there are opportunities for improvements, so ideas / progress of a partial re-implementation are tracked here.

1. [x] JGraphT / source / dev tracking integrated into OSATE
     1. [x] Following OSATE best practices, get JGraphT pulled in
     2. [x] Find a home for the source code of this project
     3. [x] Find a home for project dev metadata
2. [x] Flattened Graph Definitions
    1. [x] Update Awas Definitions (Definitions 1-4 of [the paper](https://link.springer.com/article/10.1007/s11334-021-00410-w)) to use subgraphs / flattened structure 
3. [x] Hand-built model
     1. [x] Hardcode a driver/stub class that creates a graph based on a simple AADL model. Probably the PulseOx Forwarding Application.
4. [ ] Automated testing infrastructure
5. [x] Model translation
6. [ ] Automated building infrastructure
7. [ ] Set up ZenHub project tracker
