### ISSUE TITLE
OSATE user interface is inconsistent

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#914]
Umbrella issue for enhancements to the UI, needs to be elaborated into a set of detailed issues

- [x] Create wizards for all file types
- [x] Inconsistent way of invoking commands on model elements
- [x] Provide consistent organization of commends in main menu, tool bar, context menus
- [ ] Split UI into several perspectives (AADL Modeling, Model Analysis, AGREE/Resolute ?)
- [x] Create/update user documentation
