### ISSUE TITLE
Workflow support is incomplete

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#917]
Umbrella issue for enhancements to the analysis workflows, needs to be elaborated into a set of detailed issues

- [ ] Make workflows open source if possible
- [ ] Update workflows based on AIPD feedback
- [ ] Add workflows for additional safety analyses (FMEA, FTA, ...)
- [ ] Improve user documentation
